apiVersion: apps/v1
kind: Deployment
metadata:
  name: polyverse
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: polyverse
          image: polyverse/node-echo-server
          ports:
            - containerPort: 8080
              protocol: TCP